# Generated by Django 4.1.5 on 2023-02-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('long_title', models.TextField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('website_link', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=255)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='website.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/images')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.website')),
            ],
        ),
    ]
