# Generated by Django 4.1.5 on 2023-02-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_website_live_website_order_website_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
