# Generated by Django 4.1.5 on 2023-02-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
