# Generated by Django 4.1.5 on 2023-02-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_websitebluredimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteBluredImage',
            new_name='WebsiteBlurredImage',
        ),
    ]
